remote_theme: "pages-themes/slate@v0.2.0"

title: "Financial Modeling & Analytics Portfolio "
description: >
  This site provides links to my finance
  and programming projects. 

show_downloads: true  # Set to false if you don't want to show a download link.

google_analytics: "G-K5YB2DF124"  # Replace with your actual Google Analytics tracking ID.

elements:
  - "h1"
  - "h2"
  - "h3"
  - "p"

styles:
  white-space: "nowrap"
  text-align: "left"
  overflow: "hidden"
  text-overflow: "ellipsis"

include: ["Assets/github/workflows/Assets"]
include: ["assets/css/style.scss"]
  
